version: '3.8'

networks:
  cenobridge:
    external:
      name: host
  caddy:
    driver: overlay
    driver_opts:
      encrypted: ""
    attachable: true
    name: caddy
  mail:
    driver: overlay
    driver_opts:
      encrypted: ""
    attachable: true
    name: mail
volumes:
  bridge_storage:
  caddy_data:
    external: true
  caddy_config:
    external: true
  synapse_data:
    external: true
  mailadm_db:
  certs_data:
services:
  # ceno-client "bridge" service is below
  bridge:
    image: equalitie/ceno-client:latest
    networks:
      - cenobridge
    volumes:
      - bridge_storage:/var/opt/ouinet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == bridge
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # caddy acts as a reverse proxy for synapse (matrix) and deltachat (dchat)
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
    environment:
          DWEB_DOMAIN: "${DWEB_DOMAIN}"
    configs:
      - source: caddy-caddyfile-config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == caddy
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # synapse is a matrix homeserver running as a service
  synapse:
    image: matrixdotorg/synapse:v1.52.0
    volumes:
      - synapse_data:/data
    networks:
      - caddy
    environment:
      SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"
    depends_on:
      - caddy
    configs:
      - source: synapse-homeserver-config
        target: /data/homeserver.yaml
      - source: synapse-signingkey-config
        target: /data/${DWEB_DOMAIN}.signing.key
      - source: synapse-logconfig-config
        target: /data/${DWEB_DOMAIN}.log.config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == synapse
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
# postfix is running as a part of the delta chat service
  postfix:
    image: keith/deltachat-mailadm-postfix:v0.0.1
    ports:
      - "587:587"
    volumes:
      - mailadm_db:/var/lib/mailadm/
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.crt:/certs/fullchain.pem
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.key:/certs/privkey.pem
    environment:
      MAIL_DOMAIN: "${DWEB_DOMAIN}"
    networks:
      - mail
    depends_on:
      - caddy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == caddy
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # dovecot is running as a part of the delta chat service
  dovecot:
    image: keith/deltachat-mailadm-dovecot:v0.0.1
    volumes:
      - mailadm_db:/var/lib/mailadm/
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.crt:/certs/fullchain.pem
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.key:/certs/privkey.pem
    environment:
      VMAIL_UID: "${VMAIL_UID}"
      VMAIL_GID: "${VMAIL_GID}"
    networks:
      - mail
    ports:
      - "143:143"
    depends_on:
      - caddy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == caddy
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # mailadm is running as a part of the delta chat service
  mailadm:
    image: keith/deltachat-mailadm:v0.0.1
    volumes:
      - mailadm_db:/var/lib/mailadm/
    environment:
      MAIL_DOMAIN: "${DWEB_DOMAIN}"
      VMAIL_UID: "${VMAIL_UID}"
      VMAIL_GID: "${VMAIL_GID}"
      WEB_ENDPOINT: "https://${DWEB_DOMAIN}/new_email"
    networks:
      - caddy
      - mail
    depends_on:
      - caddy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == caddy
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
configs:
  caddy-caddyfile-config:
    template_driver: golang
    file: ./conf/caddy/Caddyfile.tmpl
    external: false
  synapse-homeserver-config:
    file: ./conf/synapse/${DWEB_DOMAIN}.homeserver.yaml
    external: false
  synapse-signingkey-config:
    file: ./conf/synapse/${DWEB_DOMAIN}.signing.key
    external: false
  synapse-logconfig-config:
    file: ./conf/synapse/${DWEB_DOMAIN}.log.config
    external: false