version: '3.8'

networks:
  cenobridge:
    external:
      name: host
volumes:
  bridge_storage:
  caddy_data:
    external: true
  caddy_config:
  synapse_data:
services:
  # ceno-client "bridge" service is below
  bridge:
    image: equalitie/ceno-client:latest
    networks:
      - cenobridge
    volumes:
      - bridge_storage:/var/opt/ouinet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == bridge
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # caddy acts as a reverse proxy for synapse (matrix) and deltachat (dchat)
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - monitoring
    environment:
          DWEB_DOMAIN: "${DWEB_DOMAIN}"
    configs:
      - source: caddy-caddyfile-config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == caddy
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # synapse is a matrix homeserver running as a service
  synapse:
    image: matrixdotorg/synapse:v1.52.0
    volumes:
      - synapse_data:/data
    networks:
      - monitoring
    environment:
          SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"
    depends_on:
      - caddy
    configs:
      - source: synapse-homeserver-config
        target: /data/homeserver.yaml
      - source: synapse-signingkey-config
        target: /data/${DWEB_DOMAIN}.signing.key
      - source: synapse-logconfig-config
        target: /data/${DWEB_DOMAIN}.log.config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == synapse
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
configs:
  caddy-caddyfile-config:
    template_driver: golang
    file: ./conf/caddy/Caddyfile.tmpl
    external: false
  synapse-homeserver-config:
    template_driver: golang
    file: ./conf/${DWEB_DOMAIN}.homeserver.yaml
    external: false
  synapse-signingkey-config:
    template_driver: golang
    file: ./conf/${DWEB_DOMAIN}.signing.key
    external: false
  synapse-logconfig-config:
    template_driver: golang
    file: ./conf/${DWEB_DOMAIN}.log.config
    external: false
