version: '3.8'

networks:
  cenobridge:
    external:
      name: host
volumes:
  bridge_storage:
  caddy_data:
    external: true
  caddy_config:
services:
  # ceno-client "bridge" service is below
  bridge:
    image: equalitie/ceno-client:latest
    networks:
      - cenobridge
    volumes:
      - bridge_storage:/var/opt/ouinet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == bridge
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # caddy acts as a reverse proxy for synapse (matirx) and deltachat (dchat)
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - monitoring
    environment:
          DWEB_DOMAIN: "${DWEB_DOMAIN}"
    configs:
      - source: caddy
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == caddy
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
configs:
  caddy:
    template_driver: golang
    file: ./conf/Caddyfile.tmpl
    external: false